version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - globant_network

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    networks:
      - globant_network

  database:
    image: mongo:8.0
    container_name: database
    volumes:
      - mongo-data:/data/db
    networks:
      - globant_network

volumes:
  mongo-data: {}

networks:
  globant_network:
    driver: bridge
