services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_DEV_API_PROXY=http://backend:5000

  backend:
    build:
      context: ./backend  
      target: development
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  database:
    ports:
      - '27017:27017'

volumes:
  node_modules_frontend:
  node_modules_backend:
